In [1]:
import sklearn
import numpy as np
import matplotlib.pyplot as plt
from sklearn import decomposition, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:
# Load the data set
digits = datasets.load_digits()

# Training data set
X_digits = digits.data

# Target data set 
y_digits = digits.target


In [24]:
print(X_digits[0])

[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.   5.
   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.   0.   8.
   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.  11.   0.   1.
  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.   0.   0.   6.  13.
  10.   0.   0.   0.]


In [3]:
print(X_digits.shape)

(1797, 64)


In [4]:
print(y_digits.shape)

(1797,)


In [5]:
z = X_digits[0].copy()

In [6]:
z.shape = (8,8)
print z

[[  0.   0.   5.  13.   9.   1.   0.   0.]
 [  0.   0.  13.  15.  10.  15.   5.   0.]
 [  0.   3.  15.   2.   0.  11.   8.   0.]
 [  0.   4.  12.   0.   0.   8.   8.   0.]
 [  0.   5.   8.   0.   0.   9.   8.   0.]
 [  0.   4.  11.   0.   1.  12.   7.   0.]
 [  0.   2.  14.   5.  10.  12.   0.   0.]
 [  0.   0.   6.  13.  10.   0.   0.   0.]]


In [7]:
y_digits[0]

0

In [8]:
# for every label 1, print the row (feature vector) of X_digits 
for i in range(1797):
    if y_digits[i] == 1:
        print(X_digits[i])
        print i

[  0.   0.   0.  12.  13.   5.   0.   0.   0.   0.   0.  11.  16.   9.   0.
   0.   0.   0.   3.  15.  16.   6.   0.   0.   0.   7.  15.  16.  16.   2.
   0.   0.   0.   0.   1.  16.  16.   3.   0.   0.   0.   0.   1.  16.  16.
   6.   0.   0.   0.   0.   1.  16.  16.   6.   0.   0.   0.   0.   0.  11.
  16.  10.   0.   0.]
1
[  0.   0.   0.   0.  14.  13.   1.   0.   0.   0.   0.   5.  16.  16.   2.
   0.   0.   0.   0.  14.  16.  12.   0.   0.   0.   1.  10.  16.  16.  12.
   0.   0.   0.   3.  12.  14.  16.   9.   0.   0.   0.   0.   0.   5.  16.
  15.   0.   0.   0.   0.   0.   4.  16.  14.   0.   0.   0.   0.   0.   1.
  13.  16.   1.   0.]
11
[  0.   0.   0.   2.  16.  16.   2.   0.   0.   0.   0.   4.  16.  16.   2.
   0.   0.   1.   4.  12.  16.  12.   0.   0.   0.   7.  16.  16.  16.  12.
   0.   0.   0.   0.   3.  10.  16.  14.   0.   0.   0.   0.   0.   8.  16.
  12.   0.   0.   0.   0.   0.   6.  16.  16.   2.   0.   0.   0.   0.   2.
  12.  15.   4.   0.]
21
[  0.   0.   0

702
[  0.   0.   0.  10.  12.   8.   1.   0.   0.   0.   5.  16.  16.  16.   0.
   0.   0.   0.  10.  16.  16.   9.   0.   0.   0.   2.  15.  16.  13.   2.
   0.   0.   0.   4.  16.  16.   8.   0.   0.   0.   0.   1.  15.  16.   7.
   0.   0.   0.   0.   0.   9.  16.  11.   1.   0.   0.   0.   0.   0.   6.
  12.   6.   0.   0.]
716
[  0.   0.   0.  10.  16.  11.   1.   0.   0.   0.   0.  15.  16.  15.   2.
   0.   0.   0.   1.  13.  16.  14.   0.   0.   0.   0.   1.  15.  16.  12.
   0.   0.   0.   0.   0.  14.  16.   8.   0.   0.   0.   0.   0.  13.  16.
   5.   0.   0.   0.   0.   1.  14.  16.   1.   0.   0.   0.   0.   0.   8.
  15.   1.   0.   0.]
726
[  0.   0.   5.  15.  13.  12.   4.   0.   0.   0.  11.  16.  16.  14.   0.
   0.   0.   0.  16.  16.  16.   8.   0.   0.   0.   4.  16.  16.  15.   3.
   0.   0.   0.   2.  16.  16.   8.   0.   0.   0.   0.   0.  16.  15.   3.
   0.   0.   0.   0.   0.  10.  16.   4.   0.   0.   0.   0.   0.   8.  15.
   3.   0.   0.   0.]
731
[  0. 

In [19]:
mean = np.zeros_like(X_digits[0])

In [20]:
# compute the average of each vector of one number (in this loop we chose 0)
counter = 0
for i in range(1797):
    if y_digits[i] == 0:
        # add the values of the ith row to the total vector
        mean += X_digits[i]
        
        # count the number of instances of the value (in this loop we chose 0)
        counter += 1

# divide the vector values with the number of label instances (counter)
mean /= counter

In [21]:
#mean.shape = 8,8
mean

array([  0.00000000e+00,   2.24719101e-02,   4.18539326e+00,
         1.30955056e+01,   1.12977528e+01,   2.92696629e+00,
         3.37078652e-02,   0.00000000e+00,   0.00000000e+00,
         8.87640449e-01,   1.25786517e+01,   1.33707865e+01,
         1.14943820e+01,   1.13764045e+01,   9.66292135e-01,
         0.00000000e+00,   0.00000000e+00,   3.73033708e+00,
         1.42752809e+01,   5.26404494e+00,   2.10112360e+00,
         1.21685393e+01,   3.52247191e+00,   0.00000000e+00,
         0.00000000e+00,   5.29213483e+00,   1.27134831e+01,
         1.99438202e+00,   1.40449438e-01,   9.06179775e+00,
         6.44943820e+00,   0.00000000e+00,   0.00000000e+00,
         5.87078652e+00,   1.15561798e+01,   8.93258427e-01,
         4.49438202e-02,   8.77528090e+00,   7.12359551e+00,
         0.00000000e+00,   0.00000000e+00,   3.49438202e+00,
         1.32865169e+01,   1.65168539e+00,   1.53370787e+00,
         1.13089888e+01,   5.85393258e+00,   0.00000000e+00,
         0.00000000e+00,

## Standard Dev

In [37]:
stds = np.zeros_like(X_digits[0])
counter = 0
for i in range(1797):
    if y_digits[i] == 0:
        std = np.std(X_digits[i])
        counter += 1
print counter

178


## Covariance

In [46]:
def cov(X_digits, y_digits, n_label):
    counter = 0
    covariance = np.zeros((64,64))
    for i in range(1797):
        if y_digits[i] == n_label:
            
            # sum the n_label values & multiply the data by its transpose 
            covariance += np.outer(X_digits[i], X_digits[i])
            counter += 1     
                             
    return covariance * (1.0/(counter-1.0))

In [43]:
a = np.asarray([1, 2])
b = np.asarray([1, 2, 3])
np.outer(a, b)

array([[1, 2, 3],
       [2, 4, 6]])

In [47]:
sigma = cov(X_digits, y_digits, 0)

## Mahalanobis Distance

In [53]:
# Pass in each n_label vector & compute a distance 
def maha_dist(x, mu, sigma):
    
    # take the difference of each n_label vector and the mean vector
    diff = x - mu
    
    inv_sigma = np.linalg.inv(sigma)
    
    # multiply the inverse of the covariance matrix by the difference
    temp = np.dot(inv_sigma, diff)
    
    # dot functions takes care of the transpose for you b/c "dot" is the same as inner product
    return np.dot(diff, temp)

In [54]:
distance = maha_dist(X_digits[0], mean, sigma)

LinAlgError: Singular matrix

## Logistic Regression

## Train the Model

In [1]:
# Train the logistic regression model according to the two chosen classes
def train_model(X, y, a, b, ab_size):
    
    # count the number of rows for classes a & b 
    training_data = np.zeros((X.shape[0], X.shape[1]))
    
    # loop through the training rows/observations
    for i in range(X.shape[0]):
        
        # identify label a or label b in y vector
        if y[i] == a or y[i] == b:
            
            # Add the identified data to the training set
            training_data[ab_size] += X[i] 
        
            # run log reg for class a & b
            logistic = LogisticRegression()
            logistic.fit(training_data, y)
                
            #score = logistic.fit(X_train, y_train).score(X_test, y_test)
        
    #return parameter_vector

## Test the Model

In [2]:
# this does what the test model function does 
logistic.predict(X, y)

# the last step 
# count how many of the y_test match y_train


def test_model(X, y, model):
    
    # beta * x: this product computes the entire dot product for each row (no loop!)
    betax = np.dot(X, model)
        
    # compute y_hat using the logistic function, the sigmoid function 
    y_hat = 1.0 / (1.0 + np.exp(-betax))
    
    #y_hat needs to be rounded
    np.round(y_hat)
    

NameError: name 'logistic' is not defined

In [ ]:
x = np.asarray([-1, 2, 3, 4])

# component 
y_hat = 1.0/(1.0+np.exp(-x))
y_hat

# round y_hat
np.round(y_hat)

A = np.matrix([[-1, 2, 3, 4],[5, 6, 7, 8]])
A

y_hat_A = 1.0/(1.0+np.exp(-A))
y_hat_A

np.round(y_hat_A)

score = logistic.fit(X_train, y_train).score(X_test, y_test)